import { StateProvider } from '@/store/provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/theme/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  // pwa
  manifest: '/manifest.json',
  themeColor: '#000',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateProvider>
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </StateProvider>
      </body>
    </html>
  )
}
